include: package:flutter_lints/flutter.yaml

# Additional rules for GoSender project
linter:
  rules:
    # Prefer single quotes
    prefer_single_quotes: true
    
    # Require trailing commas
    require_trailing_commas: true
    
    # Avoid empty catch blocks
    empty_catches: true
    
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # File naming
    file_names: true
    
    # Documentation
    public_member_api_docs: false # Set to true for production
    
    # Avoid relative imports
    avoid_relative_lib_imports: true
    
    # Prefer final
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    
    # Code organization
    directives_ordering: true
    sort_child_properties_last: true
    
    # Performance
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_spread_collections: true
    
    # Safety
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    valid_regexps: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - lib/firebase_options.dart
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false