name: Workflow Health Monitor

on:
  schedule:
    - cron: '0 9 * * 1' # Every Monday 9am
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check last 20 workflow runs
        uses: actions/github-script@v6
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRunsForRepo({ owner: context.repo.owner, repo: context.repo.repo, per_page: 20 });
            const total = runs.data.workflow_runs.length;
            const successes = runs.data.workflow_runs.filter(r => r.conclusion === 'success').length;
            const rate = Math.round((successes/total)*100 || 0);
            console.log(`Last ${total} runs success rate: ${rate}%`);
            if (rate < 80) {
              await github.rest.issues.create({ owner: context.repo.owner, repo: context.repo.repo, title: `CI Health Alert: success rate ${rate}%`, body: `The last ${total} workflow runs have a success rate of ${rate}%. Please investigate.` });
            }
