require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Set Firebase SDK version to match @react-native-firebase packages
$FirebaseSDKVersion = '11.11.0'

platform :ios, '15.1'
prepare_react_native_project!

react_native_path = '../node_modules/react-native'

target 'Senderrappios' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # No need to manually add Firebase pods - they come from @react-native-firebase dependencies
  # The $FirebaseSDKVersion variable above ensures version consistency
  
end

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    react_native_path,
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
    end
  end

  installer.pods_project.targets.each do |target|
    if target.name == 'Turf'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      end
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |native_target|
      native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
  end

end

post_integrate do |installer|
  require 'fileutils'
  pods_root = File.join(Pod::Config.instance.installation_root.to_s, 'Pods')
  grpc_modulemap = File.join(pods_root, 'Target Support Files', 'gRPC-Core', 'gRPC-Core.modulemap')
  grpc_private_dir = File.join(pods_root, 'Headers', 'Private', 'grpc')
  grpc_private_modulemap = File.join(grpc_private_dir, 'gRPC-Core.modulemap')

  # Only create the symlink if the source exists and we can write to the destination
  if File.exist?(grpc_modulemap) && File.writable?(pods_root)
    begin
      FileUtils.mkdir_p(grpc_private_dir)
      FileUtils.ln_sf(grpc_modulemap, grpc_private_modulemap)
    rescue => e
      Pod::UI.warn "Failed to create gRPC modulemap symlink: #{e.message}"
    end
  end
end
