name: Admin Desktop bug
description: Report a bug in the Electron Admin Desktop app
title: "[Admin Desktop Bug]: "
labels:
  - type:bug
  - scope:admin-desktop
body:
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Production
        - Local dev
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true
  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: input
    id: build
    attributes:
      label: Build/Version
      placeholder: vX.Y.Z or commit hash
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14.2, Windows 11
