name: Documentation update
description: Request documentation changes or additions
title: "[Docs]: "
labels:
  - type:docs
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Project plan
        - Architecture
        - Development
        - Deployment
        - API reference
        - Security
        - README/Onboarding
        - Other docs
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true
  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: change
    attributes:
      label: Requested change
      description: What should be updated or added?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet the outcomes that define done.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related docs, issues, or PRs.
