name: Feature request
description: Request a new feature or enhancement
title: "[Feature]: "
labels:
  - type:feature
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Admin app
        - Admin desktop
        - Courier app
        - Marketplace app
        - Vendor app
        - Landing/marketing
        - Web app
        - Firebase backend
        - Shared packages
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true
  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: dropdown
    id: lifecycle
    attributes:
      label: Lifecycle milestone
      description: Select the target lifecycle milestone for this issue (optional)
      options:
        - M1 - Freeze Canonical Vocabulary
        - M2 - Enforce Transition Guards
        - M3 - Server Lifecycle Commands
        - M4 - Data Migration + Compatibility
        - M5 - Lifecycle Test Gate
        - Other
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior or solution.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet the outcomes that define done.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / blockers
      placeholder: Links to issues, designs, or API changes.
