name: Landing/Marketing bug
description: Report a bug on the landing/marketing site
title: "[Landing Bug]: "
labels:
  - bug
  - landing
body:
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Production
        - Staging
        - Local dev
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      placeholder: https://...
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome 122, Safari 17
