// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfUspCXI4-IESvMHeu-7CV-BWjpWLSZ8',
    appId: '1:92006199493:web:6342270d7a40a312aa00ac',
    messagingSenderId: '92006199493',
    projectId: 'gosenderr-6773f',
    authDomain: 'gosenderr-6773f.firebaseapp.com',
    storageBucket: 'gosenderr-6773f.firebasestorage.app',
    measurementId: 'G-MH358C9DP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfuu6glI4XLs3hPjr0xgcjQ-IdUcJfu7g',
    appId: '1:92006199493:android:10d1893f1b25e645aa00ac',
    messagingSenderId: '92006199493',
    projectId: 'gosenderr-6773f',
    storageBucket: 'gosenderr-6773f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPN2ZnbYhRIlTwNRKPJL37WJeFXOdQkBI',
    appId: '1:92006199493:ios:d7220f9626a45bf7aa00ac',
    messagingSenderId: '92006199493',
    projectId: 'gosenderr-6773f',
    storageBucket: 'gosenderr-6773f.firebasestorage.app',
    iosClientId: '92006199493-t1q9jfvous2ebka615herujebsjb4u6h.apps.googleusercontent.com',
    iosBundleId: 'com.papadev.gosenderr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPN2ZnbYhRIlTwNRKPJL37WJeFXOdQkBI',
    appId: '1:92006199493:ios:2e8586df998ade9baa00ac',
    messagingSenderId: '92006199493',
    projectId: 'gosenderr-6773f',
    storageBucket: 'gosenderr-6773f.firebasestorage.app',
    iosClientId: '92006199493-m98t69siftgr3ng19ieo52frlhftsui0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gosenderr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqfUspCXI4-IESvMHeu-7CV-BWjpWLSZ8',
    appId: '1:92006199493:web:fa39b1e043de62a1aa00ac',
    messagingSenderId: '92006199493',
    projectId: 'gosenderr-6773f',
    authDomain: 'gosenderr-6773f.firebaseapp.com',
    storageBucket: 'gosenderr-6773f.firebasestorage.app',
    measurementId: 'G-VL19JJYNDC',
  );
}
