#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$ROOT_DIR/apps/courieriosnativeclean"
IOS_DIR="$APP_DIR/ios"
PODFILE="$IOS_DIR/Podfile"
LOCKFILE="$IOS_DIR/Podfile.lock"
OUT_FILE="$ROOT_DIR/docs/senderr_app/NATIVE_DEPENDENCY_AUDIT.md"

if [[ "${1:-}" == "--" ]]; then
  shift
fi

MODE="${1:-generate}"

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

check_file() {
  [[ -f "$1" ]] || fail "missing file: $1"
}

resolved_pkg_version() {
  local pkg="$1"
  (
    cd "$APP_DIR" &&
      node -e "try { console.log(require('${pkg}/package.json').version); } catch (e) { console.log('missing'); }"
  )
}

pod_version() {
  local pod="$1"
  local line
  line="$(grep -E "^  - ${pod}( |/| \\()" "$LOCKFILE" | head -n1 || true)"
  if [[ -z "$line" ]]; then
    echo "missing"
    return
  fi
  echo "$line" | sed -E 's/.*\(([^)]+)\).*/\1/'
}

check_file "$PODFILE"
check_file "$LOCKFILE"

grep -q "platform :ios, '16.0'" "$PODFILE" || fail "Podfile does not pin iOS 16.0"
grep -Eq "IPHONEOS_DEPLOYMENT_TARGET.*=[[:space:]]*'16\\.0'" "$PODFILE" || fail "Podfile missing deployment target override in post_install"

react_native_ver="$(resolved_pkg_version react-native)"
react_ver="$(resolved_pkg_version react)"
firebase_ver="$(resolved_pkg_version firebase)"
geo_ver="$(resolved_pkg_version @react-native-community/geolocation)"
storage_ver="$(resolved_pkg_version @react-native-async-storage/async-storage)"

firebase_core_pod="$(pod_version FirebaseCore)"
firebase_core_internal_pod="$(pod_version FirebaseCoreInternal)"
google_utils_pod="$(pod_version GoogleUtilities)"
react_pod="$(pod_version React)"
react_core_pod="$(pod_version React-Core)"
rct_folly_pod="$(pod_version RCT-Folly)"
hermes_pod="$(pod_version hermes-engine)"

generate_report() {
  cat <<EOF
# iOS Native Dependency Audit (Senderr)

Generated by \`bash scripts/ios-dependency-audit.sh\`.

## Audit metadata

- Timestamps intentionally omitted to keep this report deterministic; use git history for last-update time.
- App path: \`apps/courieriosnativeclean\`
- Baseline target: iOS 16.0

## iOS target compatibility checks

- Podfile platform pin (\`platform :ios, '16.0'\`): Pass
- Pod deployment override in post_install (\`IPHONEOS_DEPLOYMENT_TARGET = '16.0'\`): Pass

## Native dependency versions (Pods)

| Dependency | Version | iOS 16 status | Notes |
| --- | --- | --- | --- |
| FirebaseCore | ${firebase_core_pod} | Compatible (expected) | Locked in Podfile.lock |
| FirebaseCoreInternal | ${firebase_core_internal_pod} | Compatible (expected) | Locked in Podfile.lock |
| GoogleUtilities | ${google_utils_pod} | Compatible (expected) | Locked in Podfile.lock |
| React | ${react_pod} | Compatible (expected) | RN podset version |
| React-Core | ${react_core_pod} | Compatible (expected) | RN podset version |
| RCT-Folly | ${rct_folly_pod} | Compatible (expected) | RN dependency |
| hermes-engine | ${hermes_pod} | Compatible (expected) | JS engine pod |

## Native runtime package versions (React Native app)

| Package | Version | iOS 16 status | Notes |
| --- | --- | --- | --- |
| react-native | ${react_native_ver} | Compatible (expected) | App runtime baseline |
| react | ${react_ver} | Compatible (expected) | Paired with RN |
| firebase | ${firebase_ver} | Compatible (expected) | JS SDK used by app |
| @react-native-community/geolocation | ${geo_ver} | Compatible (expected) | Device location |
| @react-native-async-storage/async-storage | ${storage_ver} | Compatible (expected) | Offline fallback storage |

## Recommended actions

1. No mandatory version bump identified from current lock state.
2. Re-run this audit after any Podfile.lock or RN version change.
3. If iOS target changes, update Podfile and regenerate this report.
EOF
}

case "$MODE" in
  generate)
    generate_report >"$OUT_FILE"
    echo "wrote $OUT_FILE"
    ;;
  check)
    check_file "$OUT_FILE"
    tmp_file="$(mktemp)"
    trap 'rm -f "$tmp_file"' EXIT
    generate_report >"$tmp_file"
    if ! cmp -s "$OUT_FILE" "$tmp_file"; then
      echo "FAIL: audit report is out of date: $OUT_FILE" >&2
      echo "Run: pnpm run ios:audit:deps" >&2
      git --no-pager diff --no-index -- "$OUT_FILE" "$tmp_file" || true
      exit 1
    fi
    echo "PASS: audit report is up to date"
    ;;
  *)
    fail "unknown mode '$MODE' (expected: generate or check)"
    ;;
esac
